'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import type { PlaybookSearchResult } from '@/lib/playbook/search'

export function AskPlaybook() {
  const [question,setQuestion] = useState(''); const [answer,setAnswer] = useState<string | null>(null); const [citations,setCitations] = useState<PlaybookSearchResult[]>([]); const [message,setMessage] = useState<string | null>(null); const [busy,setBusy] = useState(false)
  async function ask(event: FormEvent) { event.preventDefault(); if (question.trim().length < 2) return; setBusy(true); setMessage(null); setAnswer(null); const response = await fetch('/api/admin/playbook/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})}); const payload = await response.json().catch(() => ({})); if (response.ok) { setAnswer(payload.data?.answer ?? null); setMessage(payload.data?.message ?? (payload.data?.noAnswer ? 'No approved answer exists in the guidance you can access.' : null)); setCitations(payload.data?.citations ?? []) } else setMessage(payload.error || 'Ask The Playbook is unavailable'); setBusy(false) }
  return <div className="mt-6"><form onSubmit={ask} className="rounded-xl border border-[color:var(--border)] bg-[color:var(--panel)] p-5"><label className="text-[11px] font-bold uppercase tracking-[.1em] text-[color:var(--ink-3)]">Your question<textarea value={question} onChange={event => setQuestion(event.target.value)} rows={4} maxLength={1000} placeholder="What does approved Funūn doctrine say about…" className="mt-2 block w-full resize-y rounded-lg border border-[color:var(--border)] bg-[color:var(--panel-2)] px-4 py-3 text-[13px] normal-case tracking-normal" /></label><button disabled={busy || question.trim().length < 2} className="mt-3 rounded-lg px-4 py-2 text-[11px] font-extrabold text-white disabled:opacity-50" style={{background:'var(--grad)'}}>{busy ? 'Checking approved guidance…' : 'Ask The Playbook'}</button></form>{answer && <article className="mt-4 rounded-xl border border-[color:var(--indigo)] bg-[color:var(--panel)] p-5"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[color:var(--indigo)]">Grounded answer</p><p className="mt-3 whitespace-pre-wrap text-[13px] leading-7 text-[color:var(--ink-2)]">{answer}</p></article>}{message && <p role="status" className="mt-4 rounded-xl border border-[color:var(--border)] p-4 text-[12px] text-[color:var(--ink-2)]">{message}</p>}{citations.length > 0 && <section className="mt-4"><h2 className="text-[12px] font-extrabold text-[color:var(--ink)]">Approved sources</h2><div className="mt-2 grid gap-2 sm:grid-cols-2">{citations.map((source,index) => <Link key={`${source.entryId}-${source.sectionId ?? index}`} href={`/admin/playbook/${source.roomKey}/${source.slug}${source.sectionId ? `#${source.sectionId}`:''}`} className="rounded-lg border border-[color:var(--border)] bg-[color:var(--panel)] p-3 text-[11px] text-[color:var(--ink-2)] hover:border-[color:var(--indigo)]"><span className="font-bold text-[color:var(--ink)]">Source {index+1}: {source.title}</span><span className="mt-1 block text-[color:var(--ink-3)]">{source.roomLabel}{source.section ? ` · ${source.section}`:''} · revision {source.revisionNumber}</span></Link>)}</div></section>}<p className="mt-4 text-[10.5px] leading-5 text-[color:var(--ink-3)]">Answers are retrieval aids, not new doctrine or authorization. Verify material decisions in the cited published entry.</p></div>
}
