'use client'

import Link from 'next/link'
import { useState } from 'react'

export type LearningPathCard = { id: string; title: string; description: string; roomLabel: string; dueAt: string | null; steps: Array<{ id: string; label: string; entryHref: string; revision: number; knowledgePrompt: string | null; complete: boolean }> }
export function LearningPathsWorkspace({ initialPaths, schemaReady }: { initialPaths: LearningPathCard[]; schemaReady: boolean }) {
  const [paths, setPaths] = useState(initialPaths); const [responses, setResponses] = useState<Record<string,string>>({}); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  async function complete(stepId: string, needsCheck: boolean) { setBusy(stepId); setError(null); const response = await fetch(`/api/admin/playbook/learning-paths/steps/${stepId}/complete`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ response: needsCheck ? responses[stepId]?.trim() || null : null, selfConfirmed: needsCheck }) }); const payload = await response.json().catch(() => ({})); if (response.ok) setPaths(current => current.map(path => ({ ...path, steps: path.steps.map(step => step.id === stepId ? { ...step, complete: true } : step) }))); else setError(payload.error || 'Could not complete this step'); setBusy(null) }
  if (!schemaReady) return <p className="mt-6 rounded-xl border border-dashed border-[color:var(--border)] p-10 text-center text-[12px] text-[color:var(--ink-3)]">Learning Paths are built and awaiting candidate migration 206.</p>
  return <div className="mt-6 space-y-4">{paths.map(path => { const done = path.steps.filter(step => step.complete).length; const percent = path.steps.length ? Math.round(done / path.steps.length * 100) : 0; return <section key={path.id} className="rounded-xl border border-[color:var(--border)] bg-[color:var(--panel)] p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-[9.5px] font-bold uppercase tracking-[.1em] text-[color:var(--indigo)]">{path.roomLabel}</p><h2 className="mt-1 text-[17px] font-extrabold text-[color:var(--ink)]">{path.title}</h2><p className="mt-1 text-[11.5px] text-[color:var(--ink-3)]">{path.description}</p></div><p className="text-[12px] font-extrabold text-[color:var(--ink)]">{percent}% · {done}/{path.steps.length}</p></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[color:var(--panel-2)]"><div className="h-full bg-[color:var(--indigo)]" style={{ width: `${percent}%` }} /></div><ol className="mt-4 space-y-2">{path.steps.map((step,index) => <li key={step.id} className="rounded-lg border border-[color:var(--border)] bg-[color:var(--panel-2)] p-3"><div className="flex items-center gap-3"><span className="flex h-6 w-6 items-center justify-center rounded-full border border-[color:var(--border)] text-[10px]">{step.complete ? '✓' : index + 1}</span><Link href={step.entryHref} className="flex-1 text-[12px] font-bold text-[color:var(--ink)] hover:text-[color:var(--indigo)]">{step.label} · revision {step.revision}</Link>{!step.complete && !step.knowledgePrompt && <button disabled={busy !== null} onClick={() => complete(step.id,false)} className="text-[11px] font-bold text-[color:var(--indigo)]">Complete</button>}</div>{step.knowledgePrompt && !step.complete && <div className="ml-9 mt-3"><p className="text-[11px] font-bold text-[color:var(--ink-2)]">Knowledge check: {step.knowledgePrompt}</p><textarea value={responses[step.id] ?? ''} onChange={event => setResponses(current => ({ ...current, [step.id]: event.target.value }))} rows={2} className="mt-2 w-full rounded-lg border border-[color:var(--border)] bg-[color:var(--panel)] px-3 py-2 text-[11.5px]" /><button disabled={busy !== null || !responses[step.id]?.trim()} onClick={() => complete(step.id,true)} className="mt-2 text-[11px] font-bold text-[color:var(--indigo)] disabled:opacity-50">Answer and complete</button></div>}</li>)}</ol>{path.dueAt && <p className="mt-3 text-[10.5px] text-amber-300">Due {new Date(path.dueAt).toLocaleDateString('en-US')}</p>}</section>})}{paths.length === 0 && <p className="rounded-xl border border-dashed border-[color:var(--border)] p-10 text-center text-[12px] text-[color:var(--ink-3)]">No learning paths are assigned to you.</p>}{error && <p role="alert" className="text-[11px] text-rose-400">{error}</p>}</div>
}
