'use client'

import { useState } from 'react'
export type WorkflowRunCard = { id: string; title: string; contextLabel: string; roomKey: string; status: string; tasks: { id: string; label: string; status: string; required: boolean }[] }
export function WorkflowWorkbench({ runs, templates, sourceEntries, schemaReady }: { runs: WorkflowRunCard[]; templates: { id: string; title: string; roomKey: string }[]; sourceEntries: { id: string; title: string; roomKey: string }[]; schemaReady: boolean }) {
  const [cards, setCards] = useState(runs); const [message, setMessage] = useState('')
  async function start(form: HTMLFormElement) { const data = new FormData(form); const template = templates.find(item => item.id === data.get('templateId')); if (!template) return; const response = await fetch('/api/admin/playbook/workflows', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'start_run', roomKey: template.roomKey, templateId: template.id, contextType: data.get('contextType'), contextId: data.get('contextId'), contextLabel: data.get('contextLabel') }) }); const body = await response.json().catch(() => ({})); setMessage(response.ok ? 'Workflow started. Refresh to open its checklist.' : body.error ?? 'Could not start workflow') }
  async function create(form: HTMLFormElement) { const data = new FormData(form); const entry = sourceEntries.find(item => item.id === data.get('entryId')); if (!entry) return; const steps = String(data.get('steps') ?? '').split('\n').map(label => label.trim()).filter(Boolean).map(label => ({ label, required: true })); const response = await fetch('/api/admin/playbook/workflows', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'create_template', roomKey: entry.roomKey, entryId: entry.id, title: data.get('title'), steps }) }); const body = await response.json().catch(() => ({})); setMessage(response.ok ? 'Workflow template created. Refresh to start it.' : body.error ?? 'Could not create workflow') }
  async function change(run: WorkflowRunCard, taskId: string, status: string) { const response = await fetch(`/api/admin/playbook/workflows/tasks/${taskId}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ roomKey: run.roomKey, status }) }); if (!response.ok) return setMessage((await response.json().catch(() => ({}))).error ?? 'Could not update task'); setCards(current => current.map(card => card.id === run.id ? { ...card, tasks: card.tasks.map(task => task.id === taskId ? { ...task, status } : task) } : card)) }
  if (!schemaReady) return <p className="mt-5 rounded-lg border border-amber-500/30 p-4 text-sm">Workflow Workbench is ready in code and activates after candidate migration 206 is approved.</p>
  return <div className="mt-6 space-y-5">{sourceEntries.length>0&&<details className="rounded-xl border border-[color:var(--border)] p-4"><summary className="cursor-pointer font-bold">Turn published doctrine into a workflow</summary><form onSubmit={event=>{event.preventDefault();void create(event.currentTarget)}} className="mt-4 grid gap-3"><select name="entryId" required className="rounded-lg bg-[color:var(--panel-2)] p-3">{sourceEntries.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select><input name="title" required placeholder="Workflow name" className="rounded-lg bg-[color:var(--panel-2)] p-3"/><textarea name="steps" required rows={6} placeholder={'One operational step per line\nConfirm participant\nReview rights data\nLog outcome'} className="rounded-lg bg-[color:var(--panel-2)] p-3"/><button className="w-fit rounded-lg bg-[color:var(--indigo)] px-4 py-2 font-bold text-white">Create template</button></form></details>}<form onSubmit={event => { event.preventDefault(); void start(event.currentTarget) }} className="grid gap-3 rounded-xl border border-[color:var(--border)] p-4 md:grid-cols-2"><select name="templateId" required className="rounded-lg bg-[color:var(--panel-2)] p-3">{templates.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select><input name="contextLabel" required placeholder="What are you running this for?" className="rounded-lg bg-[color:var(--panel-2)] p-3"/><input name="contextType" required placeholder="Context type, e.g. onboarding" className="rounded-lg bg-[color:var(--panel-2)] p-3"/><input name="contextId" required placeholder="CRM record or project ID" className="rounded-lg bg-[color:var(--panel-2)] p-3"/><button disabled={templates.length===0} className="w-fit rounded-lg bg-[color:var(--indigo)] px-4 py-2 font-bold text-white disabled:opacity-50">Start workflow</button></form>{message && <p className="text-sm text-[color:var(--ink-3)]">{message}</p>}{cards.map(run => <section key={run.id} className="rounded-xl border border-[color:var(--border)] p-4"><div className="flex justify-between"><div><h2 className="font-bold">{run.title}</h2><p className="text-sm text-[color:var(--ink-3)]">{run.contextLabel}</p></div><span className="text-xs uppercase">{run.status}</span></div><div className="mt-3 space-y-2">{run.tasks.map(task => <label key={task.id} className="flex items-center gap-3 rounded-lg bg-[color:var(--panel-2)] p-3"><input type="checkbox" checked={task.status === 'completed'} onChange={event => void change(run, task.id, event.target.checked ? 'completed' : 'pending')} /><span className={task.status === 'completed' ? 'line-through opacity-60' : ''}>{task.label}</span>{task.required && <span className="ml-auto text-[10px] uppercase text-[color:var(--ink-3)]">Required</span>}</label>)}</div></section>)}</div>
}
