// Seeded profile for NEXT_PUBLIC_VAULT_DEMO=true — the in-memory preview
// mode the app runs in when there is no Supabase session to read from.
// Lifted out of app/(artist)/settings/page.tsx unchanged when the settings
// profile read moved up into the shared layout; it lives here so the layout
// stays readable.
import type { UserProfile } from '@/types'

export const DEMO_PROFILE: UserProfile = {
  id: '00000000-0000-0000-0000-000000000000',
  artist_name: 'Demo Artist',
  genre: 'R&B',
  genres: ['r&b'],
  location: 'Los Angeles, USA',
  bio: 'Demo profile — sign in with a real account to edit your own.',
  career_stage: 2,
  instagram_handle: '@demo',
  threads_handle: null,
  tiktok_handle: '@demo',
  spotify_url: null,
  monthly_listeners: 12500,
  total_streams: null,
  sound_identity: null,
  isrc_country_code: 'US',
  isrc_registrant_code: 'D3M',
  isrc_year_counters: { '26': 3 },
  handle: 'demo-artist',
  is_public: true,
  avatar_url: null,
  banner_url: null,
  pronouns: null,
  verified: false,
  roles: [{ kind: 'preset', slug: 'artist' }],
  open_to: ['collabs', 'sync'],
  featured_project_id: null,
  allow_resharing: true,
  member_type: 'artist',
  search_vector: null,
  profile_visibility: 'public',
  open_to_visibility: 'public',
  verified_at: null,
  legal_first_name: null,
  legal_middle_name: null,
  legal_last_name: null,
  legal_name_suffix: null,
  legal_name_locked_at: null,
  claim_prefill: null,
  contact_phone: null,
  mailing_address: null,
  industry_roles: [],
  pro: null,
  ipi: null,
  publisher: null,
  administrator: null,
  mlc_id: null,
  soundexchange_id: null,
  isni: null,
  gs1_company_prefix: null,
  grid_issuer_code: null,
  catalog_number_prefix: null,
  identifier_counters: null,
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-01-01T00:00:00Z',
}
