import { NextResponse } from 'next/server'
import { z } from 'zod'
import { verifyAdmin } from '@/lib/admin/gate'
import { isOperationalV1SchemaMissing } from '@/lib/playbook/operational-v1'
import { createServiceClient } from '@/lib/supabase/server'

const Key=z.string().regex(/^[a-z0-9][a-z0-9_-]{1,79}$/)
const Schema=z.object({action:z.enum(['enable','disable','emergency_disable','emergency_clear']),note:z.string().trim().min(1).max(4000)}).strict()
export async function PATCH(request:Request,context:{params:Promise<{key:string}>}){const key=Key.safeParse((await context.params).key);const parsed=Schema.safeParse(await request.json().catch(()=>({})));if(!key.success||!parsed.success)return NextResponse.json({error:'Invalid activation change'},{status:400});const auth=await verifyAdmin();if('error'in auth)return NextResponse.json({error:auth.error},{status:auth.status});const service=createServiceClient();const current=await service.from('playbook_feature_controls').select('enabled, emergency_disabled').eq('feature_key',key.data).maybeSingle();if(current.error){if(isOperationalV1SchemaMissing(current.error))return NextResponse.json({error:'Activation controls are built but not activated yet.'},{status:503});return NextResponse.json({error:current.error.message},{status:500})}if(!current.data)return NextResponse.json({error:'Feature not found'},{status:404});const mutation=parsed.data.action==='enable'?{enabled:true}:parsed.data.action==='disable'?{enabled:false}:parsed.data.action==='emergency_disable'?{emergency_disabled:true,disabled_reason:parsed.data.note}:{emergency_disabled:false,disabled_reason:null};const update=await service.from('playbook_feature_controls').update({...mutation,updated_by:auth.user.id,updated_at:new Date().toISOString()}).eq('feature_key',key.data);if(update.error)return NextResponse.json({error:update.error.message},{status:500});const eventType=parsed.data.action==='emergency_disable'?'emergency_disabled':parsed.data.action==='emergency_clear'?'emergency_cleared':parsed.data.action==='enable'?'enabled':'disabled';const event=await service.from('playbook_feature_control_events').insert({feature_key:key.data,event_type:eventType,actor_id:auth.user.id,note:parsed.data.note});if(event.error)return NextResponse.json({error:'Activation changed, but the audit event failed. Contact IT before proceeding.'},{status:500});return NextResponse.json({data:{saved:true}})}
