export const dynamic = 'force-dynamic'

import { redirect } from 'next/navigation'
import { ALL_STAFF_ROLES, getStaffRoles, requireStaffPage } from '@/lib/admin/gate'
import { readRoomGrants } from '@/lib/playbook/access-grants'
import { isPlaybookEnablementSchemaMissing, readinessRollup } from '@/lib/playbook/enablement'
import { resolveGovernanceRooms } from '@/lib/playbook/governance'
import { loadRooms } from '@/lib/playbook/rooms'
import { createServiceClient } from '@/lib/supabase/server'

function Metric({ label, value, caption }: { label: string; value: string | number; caption: string }) { return <div className="rounded-xl border border-[color:var(--border)] bg-[color:var(--panel)] p-5"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[color:var(--ink-3)]">{label}</p><p className="mt-2 text-3xl font-extrabold text-[color:var(--ink)]">{value}</p><p className="mt-2 text-[10.5px] leading-5 text-[color:var(--ink-3)]">{caption}</p></div> }

export default async function PlaybookReadinessPage() {
  const auth = await requireStaffPage(ALL_STAFF_ROLES); const roles = getStaffRoles(auth.user); const service = createServiceClient(); const [rooms, grants, leads] = await Promise.all([loadRooms(service), readRoomGrants(service), roles.includes('leadership') ? Promise.resolve({ data: [], error: null }) : service.from('playbook_room_leads').select('room_id').eq('user_id', auth.user.id)])
  const governed = resolveGovernanceRooms({ roles, rooms, grants, leadRoomIds: (leads.data ?? []).map(row => row.room_id as string) }); if (!governed.length) redirect('/admin/playbook'); const roomIds = governed.map(room => room.id)
  const entries = await service.from('playbook_entries').select('id, review_due_at, owner_id, status').in('room_id', roomIds); if (entries.error) throw new Error(entries.error.message); const published = (entries.data ?? []).filter(row => row.status === 'published'); const entryIds = published.map(row => row.id as string); const now = Date.now(); const stale = published.filter(row => row.review_due_at && Date.parse(row.review_due_at) <= now).length; const ownerMissing = published.filter(row => !row.owner_id).length
  const assignments = entryIds.length ? await service.from('playbook_reading_assignments').select('id, due_at').in('entry_id', entryIds).is('revoked_at', null) : { data: [], error: null }; const assignmentIds = (assignments.data ?? []).map(row => row.id as string); const acknowledgements = assignmentIds.length ? await service.from('playbook_reading_acknowledgements').select('assignment_id').in('assignment_id', assignmentIds) : { data: [], error: null }; const completedAssignmentIds = new Set((acknowledgements.data ?? []).map(row => row.assignment_id as string)); const overdue = (assignments.data ?? []).filter(row => row.due_at && Date.parse(row.due_at) < now && !completedAssignmentIds.has(row.id as string)).length
  const [feedback, paths, assistant] = await Promise.all([service.from('playbook_reader_feedback').select('id, status').in('room_id', roomIds), service.from('playbook_learning_paths').select('id').in('room_id', roomIds).eq('status','published'), entryIds.length ? service.from('playbook_assistant_runs').select('id, status').overlaps('source_entry_ids', entryIds) : Promise.resolve({ data: [], error: null })]); const schemaReady = ![feedback.error, paths.error, assistant.error].some(error => error && isPlaybookEnablementSchemaMissing(error)); const openFeedback = (feedback.data ?? []).filter(row => ['open','triaged'].includes(row.status)).length; const rollup = readinessRollup({ assigned: assignmentIds.length, completed: completedAssignmentIds.size, overdue, openFeedback, staleEntries: stale })
  return <main className="mx-auto w-full max-w-[1120px] px-6 py-[30px] pb-[60px] lg:px-9"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[color:var(--indigo)]">The Playbook · Leadership view</p><h1 className="mt-1 text-2xl font-extrabold text-[color:var(--ink)]">Learning & Readiness</h1><p className="mt-2 text-[13px] text-[color:var(--ink-3)]">Operational signals for the rooms you govern—not a productivity score for individual Team Members.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Reading completion" value={`${rollup.completionRate}%`} caption={`${completedAssignmentIds.size} acknowledged assignment sources of ${assignmentIds.length}.`} /><Metric label="Overdue reading" value={overdue} caption="Required doctrine past its due date." /><Metric label="Open feedback" value={schemaReady ? openFeedback : '—'} caption="Questions and improvement items awaiting closure." /><Metric label="Doctrine health" value={rollup.state} caption={`${stale} reviews overdue · ${ownerMissing} owner gaps.`} /></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Published guidance" value={published.length} caption={`Across ${governed.length} governed room${governed.length === 1 ? '' : 's'}.`} /><Metric label="Learning paths" value={schemaReady ? (paths.data ?? []).length : '—'} caption="Published role-based learning programs." /><Metric label="Grounded AI runs" value={schemaReady ? (assistant.data ?? []).length : '—'} caption="Questions answered from authorized doctrine sources." /></div>{!schemaReady && <p className="mt-4 text-[11px] text-amber-300">The expanded readiness signals activate with candidate migration 206.</p>}</main>
}
