import { NextResponse } from 'next/server'
import { createApiClient } from '@/lib/supabase/server'
import { generateApprovalToken, APPROVAL_TOKEN_EXPIRY_DAYS } from '@/lib/split-sheets/approval'
import { sendEmail } from '@/lib/email'

// ─── POST /api/collaborators/[id]/invite ─────────────────────────────────
// Sends an educational IPI-invite email to the collaborator with a tokenized
// link to /signup?invite=[token]. Enforces a 24h cooldown per collaborator+
// inviting user pair to prevent duplicate emails (T-01-15, Pitfall 4).
export async function POST(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  // ── 1. Auth gate ─────────────────────────────────────────────────────
  const supabase = await createApiClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { id } = await params

  // ── 2. Load collaborator — must be owned by the requesting user ──────
  const { data: collaborator, error: collabError } = await supabase
    .from('collaborators')
    .select('id, user_id, name, email')
    .eq('id', id)
    .eq('user_id', user.id)
    .maybeSingle()

  if (collabError || !collaborator) {
    return NextResponse.json({ error: 'Not found or not authorized' }, { status: 404 })
  }

  // ── 3. Require email — cannot invite without an address ──────────────
  if (!collaborator.email) {
    return NextResponse.json(
      { error: 'A collaborator email address is required to send an invite' },
      { status: 400 }
    )
  }

  // ── 4. 24h cooldown — suppress duplicate invites (T-01-15, Pitfall 4) ─
  const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString()
  const { data: recentInvite } = await supabase
    .from('collaborator_invites')
    .select('id')
    .eq('collaborator_id', id)
    .eq('inviting_user_id', user.id)
    .gte('sent_at', since)
    .maybeSingle()

  if (recentInvite) {
    return NextResponse.json({ ok: true, skipped: true })
  }

  // ── 5. Generate invite token and insert invite record ─────────────────
  const inviteToken = generateApprovalToken()
  const expiresAt = new Date()
  expiresAt.setDate(expiresAt.getDate() + APPROVAL_TOKEN_EXPIRY_DAYS)

  const { error: insertError } = await supabase.from('collaborator_invites').insert({
    collaborator_id: id,
    inviting_user_id: user.id,
    invited_email: collaborator.email,
    invite_token: inviteToken,
    status: 'pending',
    token_expires_at: expiresAt.toISOString(),
  })

  if (insertError) {
    return NextResponse.json({ error: insertError.message }, { status: 500 })
  }

  // ── 6. Send educational IPI invite email (D-04, D-08) ────────────────
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? ''
  const inviteUrl = `${appUrl}/signup?invite=${inviteToken}`
  const joinUrl = `${appUrl}/join/${inviteToken}`

  const result = await sendEmail({
    to: collaborator.email,
    subject: `You've been added as a collaborator on Funūn — claim your profile`,
    html: `
      <h2>Hi ${collaborator.name},</h2>
      <p>An artist has added you as a collaborator on <strong>Funūn</strong>. You can view your collaborator profile and make sure everything is accurate.</p>

      <h3>What is an IPI/CAE number?</h3>
      <p>An <strong>IPI (Interested Party Information)</strong> number is a unique identifier assigned to songwriters and publishers by Performing Rights Organizations (PROs). It's essential for tracking royalty payments across borders.</p>

      <p><strong>Why it matters for you:</strong> Without an IPI number, royalties generated by your compositions may not be correctly attributed or paid to you — especially for international streams and performances.</p>

      <h3>How to get your IPI number</h3>
      <ul>
        <li><strong>ASCAP (US):</strong> Register at <a href="https://www.ascap.com/membership">ascap.com/membership</a></li>
        <li><strong>BMI (US):</strong> Register at <a href="https://www.bmi.com/creators">bmi.com/creators</a></li>
        <li><strong>SESAC (US):</strong> Apply at <a href="https://www.sesac.com/affiliates">sesac.com/affiliates</a></li>
        <li><strong>SOCAN (Canada):</strong> Register at <a href="https://www.socan.com/join">socan.com/join</a></li>
      </ul>
      <p>Once you're registered with a PRO, they will assign you an IPI number that you can add to your Funūn profile.</p>

      <h3>View your collaborator profile</h3>
      <p>The artist has recorded your information. You can view it and flag any corrections here:</p>
      <p><a href="${joinUrl}" style="display:inline-block;padding:10px 20px;background:#818CF8;color:#fff;border-radius:8px;text-decoration:none;font-weight:600">View my collaborator profile</a></p>

      <h3>Create your Funūn account</h3>
      <p>Join Funūn to manage your rights, track your registrations, and keep your collaborator data up to date:</p>
      <p><a href="${inviteUrl}">Create your Funūn account →</a></p>

      <p style="color:#888;font-size:12px">This link expires in ${APPROVAL_TOKEN_EXPIRY_DAYS} days.</p>
    `,
    text: [
      `Hi ${collaborator.name},`,
      '',
      'An artist has added you as a collaborator on Funūn.',
      '',
      'ABOUT YOUR IPI/CAE NUMBER',
      'An IPI number is assigned by your Performing Rights Organization (PRO). Without one, royalties from your compositions may not reach you.',
      '',
      'Register with: ASCAP (ascap.com/membership), BMI (bmi.com/creators), SESAC (sesac.com/affiliates), or SOCAN (socan.com/join)',
      '',
      `View your collaborator profile: ${joinUrl}`,
      `Create your Funūn account: ${inviteUrl}`,
    ].join('\n'),
  })

  if (!result.ok) {
    // Email not configured or failed — still return ok (best-effort)
    return NextResponse.json({ ok: true, emailSent: false })
  }

  return NextResponse.json({ ok: true, emailSent: true })
}
