import { generateApprovalToken, APPROVAL_TOKEN_EXPIRY_DAYS } from '@/lib/split-sheets/approval'
import { sendEmail } from '@/lib/email'
import { esc } from '@/lib/email/esc'
import { resolveAccountIdByEmail } from '@/lib/invites/allowlist'
import { createConnectionRequest, BLOCKED_ACTION_ERROR, BLOCKED_ACTION_STATUS } from '@/lib/social/connect-request'
import { linkClaimedCollaborators } from '@/lib/collaborators/link-claim'
import { createServiceClient } from '@/lib/supabase/server'
import type { SupabaseClient } from '@supabase/supabase-js'

// ─── Shared collaborator-invite mechanics ────────────────────────────────
// Extracted out of app/api/collaborators/[id]/invite/route.ts (260825-i4i)
// so a second caller (the quick-invite route) can send the exact same
// educational IPI-invite email and reuse the exact same 60s-cooldown /
// token-insert / best-effort-send logic, rather than a second, drifting
// copy of it.
//
// M6 (27-CODEX-REVIEW.md): collaborator.name is artist-entered, user-
// controlled free text and was previously interpolated into this email's
// HTML body unescaped — an artist could plant markup/script in a
// collaborator's name field that would render in the recipient's mail
// client. Every interpolated value below is escaped via lib/email/esc.ts
// (the same helper the branded artistInvite/artistSpotOpened/
// artistReopened templates use). That escaping rationale moves here with
// the email builder — it now lives at the point where the values are
// actually interpolated.
//
// 260825-m2k: sendCollaboratorInvite now decides, BEFORE any signup token
// is minted, whether the collaborator's email already belongs to a Funūn
// account. If it does, this sends a collaborator connection request
// through the shared lib/social/connect-request.ts machinery instead of a
// "join Funūn" signup invite — see the outcome branch below.

// ─── URL builders ─────────────────────────────────────────────────────────

/**
 * Strips a trailing slash off NEXT_PUBLIC_APP_URL the same way approveUrl
 * in lib/split-sheets/esign-invite.ts does. A missing base URL yields a
 * relative path rather than the string "undefined/…" — a broken link is
 * recoverable, a link that visibly reads "undefined" destroys the trust
 * signal this message depends on.
 */
function appBase(): string {
  return (process.env.NEXT_PUBLIC_APP_URL ?? '').replace(/\/+$/, '')
}

/** Builds the artist-facing signup link a collaborator uses to claim their profile. */
export function buildCollaboratorInviteUrl(token: string): string {
  return `${appBase()}/signup?invite=${token}`
}

/** Builds the read-only "view my collaborator profile" link. */
export function buildCollaboratorJoinUrl(token: string): string {
  return `${appBase()}/join/${token}`
}

// ─── Email builder ─────────────────────────────────────────────────────────

export type CollaboratorInviteEmail = { subject: string; html: string; text: string }

/**
 * Renders the educational IPI-invite email body. Pure — reads only its
 * input, touches no network, and never throws. Moved byte-for-byte from
 * the item route, including every esc() call and the
 * APPROVAL_TOKEN_EXPIRY_DAYS expiry footnote.
 */
export function buildCollaboratorInviteEmail(input: {
  name: string
  token: string
}): CollaboratorInviteEmail {
  const inviteUrl = buildCollaboratorInviteUrl(input.token)
  const joinUrl = buildCollaboratorJoinUrl(input.token)

  // M6: escape every interpolated value before it lands in the HTML body —
  // collaborator.name is artist-entered free text; joinUrl/inviteUrl embed
  // a generated token but are escaped defensively too (esc() is a no-op on
  // already-safe input).
  const safeName = esc(input.name)
  const safeJoinUrl = esc(joinUrl)
  const safeInviteUrl = esc(inviteUrl)

  return {
    subject: `You've been added as a collaborator on Funūn — claim your profile`,
    html: `
      <h2>Hi ${safeName},</h2>
      <p>An artist has added you as a collaborator on <strong>Funūn</strong>. You can view your collaborator profile and make sure everything is accurate.</p>

      <h3>What is an IPI/CAE number?</h3>
      <p>An <strong>IPI (Interested Party Information)</strong> number is a unique identifier assigned to songwriters and publishers by Performing Rights Organizations (PROs). It's essential for tracking royalty payments across borders.</p>

      <p><strong>Why it matters for you:</strong> Without an IPI number, royalties generated by your compositions may not be correctly attributed or paid to you — especially for international streams and performances.</p>

      <h3>How to get your IPI number</h3>
      <ul>
        <li><strong>ASCAP (US):</strong> Register at <a href="https://www.ascap.com/membership">ascap.com/membership</a></li>
        <li><strong>BMI (US):</strong> Register at <a href="https://www.bmi.com/creators">bmi.com/creators</a></li>
        <li><strong>SESAC (US):</strong> Apply at <a href="https://www.sesac.com/affiliates">sesac.com/affiliates</a></li>
        <li><strong>SOCAN (Canada):</strong> Register at <a href="https://www.socan.com/join">socan.com/join</a></li>
      </ul>
      <p>Once you're registered with a PRO, they will assign you an IPI number that you can add to your Funūn profile.</p>

      <h3>View your collaborator profile</h3>
      <p>The artist has recorded your information. You can view it and flag any corrections here:</p>
      <p><a href="${safeJoinUrl}" style="display:inline-block;padding:10px 20px;background:#818CF8;color:#fff;border-radius:8px;text-decoration:none;font-weight:600">View my collaborator profile</a></p>

      <h3>Create your Funūn account</h3>
      <p>Join Funūn to manage your rights, track your registrations, and keep your collaborator data up to date:</p>
      <p><a href="${safeInviteUrl}">Create your Funūn account →</a></p>

      <p style="color:#888;font-size:12px">This link expires in ${APPROVAL_TOKEN_EXPIRY_DAYS} days.</p>
    `,
    text: [
      `Hi ${input.name},`,
      '',
      'An artist has added you as a collaborator on Funūn.',
      '',
      'ABOUT YOUR IPI/CAE NUMBER',
      'An IPI number is assigned by your Performing Rights Organization (PRO). Without one, royalties from your compositions may not reach you.',
      '',
      'Register with: ASCAP (ascap.com/membership), BMI (bmi.com/creators), SESAC (sesac.com/affiliates), or SOCAN (socan.com/join)',
      '',
      `View your collaborator profile: ${joinUrl}`,
      `Create your Funūn account: ${inviteUrl}`,
    ].join('\n'),
  }
}

// ─── Connect-request email builder ─────────────────────────────────────────

/**
 * A collaborator connection request, NOT an onboarding invite: the
 * recipient already has a Funūn account, so this email points them at the
 * request waiting in their notifications rather than at a signup link.
 * Contains no signup link, no token, and none of the IPI onboarding
 * material — that content is for people who do not have an account yet.
 * Every interpolated value is escaped via esc() for the same reason
 * buildCollaboratorInviteEmail escapes its inputs: inviterName comes from
 * user_profiles.artist_name and collaboratorName is artist-entered free
 * text.
 */
export function buildCollaboratorConnectEmail(input: {
  inviterName: string
  collaboratorName: string
}): CollaboratorInviteEmail {
  const safeInviterName = esc(input.inviterName)
  const safeCollaboratorName = esc(input.collaboratorName)
  const networkUrl = esc(`${appBase()}/network`)

  return {
    subject: `${input.inviterName} wants to add you as a collaborator on Funūn`,
    html: `
      <h2>Hi ${safeCollaboratorName},</h2>
      <p><strong>${safeInviterName}</strong> wants to add you as a collaborator on <strong>Funūn</strong>.</p>
      <p>The request is waiting in your Funūn notifications, where you can accept or decline it.</p>
      <p><a href="${networkUrl}" style="display:inline-block;padding:10px 20px;background:#818CF8;color:#fff;border-radius:8px;text-decoration:none;font-weight:600">View the request</a></p>
    `,
    text: [
      `Hi ${input.collaboratorName},`,
      '',
      `${input.inviterName} wants to add you as a collaborator on Funūn.`,
      '',
      'The request is waiting in your Funūn notifications, where you can accept or decline it.',
      '',
      `View it: ${appBase()}/network`,
    ].join('\n'),
  }
}

// The note attached to a collaborator connection request is server-owned —
// never taken from the request body, since it becomes the notification's
// body text and must not be artist-authored (T-m2k-05).
export const COLLABORATOR_CONNECT_NOTE = 'Would like to add you as a collaborator on Funūn.'

// ─── Send helper ─────────────────────────────────────────────────────────

export type CollaboratorInviteResult =
  | { ok: false; status: number; error: string }
  | { ok: true; outcome: 'invited'; inviteLink: string; emailSent: boolean; skipped: boolean }
  | { ok: true; outcome: 'connect-requested'; emailSent: boolean }
  | { ok: true; outcome: 'connect-pending' }
  | { ok: true; outcome: 'already-connected' }
  | { ok: true; outcome: 'already-linked' }

/**
 * Sends (or best-effort re-sends) an educational IPI-invite email for a
 * collaborator, and always hands the caller back a usable
 * /signup?invite=<token> link — because a failed or unconfigured email
 * send must never read as a failed invite (Resend is currently down in
 * prod: invalid API key + unverified sender).
 *
 * `supabase` is the caller's already-authenticated client — ownership of
 * the collaborator row is proven by the caller BEFORE this function runs
 * (the item route filters `.eq('user_id', user.id)`; the quick-invite
 * route creates/reuses a row it already scoped to `user.id`). This
 * function does not re-check ownership; it trusts the caller's query.
 *
 * 260825-m2k: before any of the above runs, this now decides whether the
 * collaborator's email already belongs to a Funūn account. Nothing about
 * tokens may run until membership is known — this branch sits immediately
 * after the email guard and BEFORE the 60s cooldown lookup.
 */
export async function sendCollaboratorInvite(
  supabase: SupabaseClient,
  input: {
    collaborator: { id: string; name: string; email: string | null; claimed_by?: string | null }
    invitingUserId: string
  }
): Promise<CollaboratorInviteResult> {
  const { collaborator, invitingUserId } = input

  // ── 1. Require email — cannot invite without an address ──────────────
  if (!collaborator.email) {
    return {
      ok: false,
      status: 400,
      error: 'A collaborator email address is required to send an invite',
    }
  }

  // ── 1b. Membership branch (260825-m2k) — decided before any token work. ──

  // a. Already claimed — nothing to send, nothing to look up.
  if (collaborator.claimed_by) {
    return { ok: true, outcome: 'already-linked' }
  }

  // b. Resolve the email to an account id. A lookup FAILURE is a hard stop —
  //    it must never fall through to the signup path, because that would
  //    silently resend a "join Funūn" email to someone who already has an
  //    account (the exact bug this branch exists to fix).
  const service = createServiceClient()
  const resolved = await resolveAccountIdByEmail(service, collaborator.email)
  if (!resolved.ok) {
    return {
      ok: false,
      status: 503,
      error: 'Funūn could not check that email address right now — try again in a moment.',
    }
  }

  if (resolved.userId) {
    // d. The email is the inviter's own account.
    if (resolved.userId === invitingUserId) {
      return {
        ok: false,
        status: 400,
        error: 'That email address belongs to your own account.',
      }
    }

    // e. An existing Funūn member — send a connection request instead of a
    //    signup invite.
    const connectResult = await createConnectionRequest(supabase, service, {
      requesterId: invitingUserId,
      addresseeId: resolved.userId,
      note: COLLABORATOR_CONNECT_NOTE,
    })

    switch (connectResult.kind) {
      case 'created': {
        const email = buildCollaboratorConnectEmail({
          inviterName: connectResult.actorName,
          collaboratorName: collaborator.name,
        })
        const sendResult = await sendEmail({ to: collaborator.email, ...email })
        return { ok: true, outcome: 'connect-requested', emailSent: sendResult.ok }
      }
      case 'pending':
        return { ok: true, outcome: 'connect-pending' }
      case 'connected':
      case 'connected-conflict': {
        const linked = await linkClaimedCollaborators(service, {
          ownerUserId: invitingUserId,
          memberUserId: resolved.userId,
          memberEmail: collaborator.email,
        })
        return { ok: true, outcome: linked > 0 ? 'already-linked' : 'already-connected' }
      }
      case 'blocked':
        return { ok: false, status: BLOCKED_ACTION_STATUS, error: BLOCKED_ACTION_ERROR }
      case 'self':
        return { ok: false, status: 400, error: 'That email address belongs to your own account.' }
      case 'error':
        return { ok: false, status: 500, error: connectResult.message }
    }
  }

  // c. No account on this email — fall through to the existing signup-invite
  //    path, untouched below.

  // ── 2. Short cooldown — a light guard against accidental double-sends only.
  //      A deliberate "Resend invite" (>60s later) DOES re-send: artists
  //      legitimately need to nudge a collaborator who missed the first email
  //      (was a 24h silent block — T-01-15/Pitfall 4 — relaxed for resend UX).
  const since = new Date(Date.now() - 60 * 1000).toISOString()
  const { data: recentInvite } = await supabase
    .from('collaborator_invites')
    .select('id, invite_token')
    .eq('collaborator_id', collaborator.id)
    .eq('inviting_user_id', invitingUserId)
    .gte('sent_at', since)
    .maybeSingle()

  if (recentInvite) {
    return {
      ok: true,
      outcome: 'invited',
      skipped: true,
      emailSent: false,
      inviteLink: buildCollaboratorInviteUrl(
        (recentInvite as { invite_token: string }).invite_token
      ),
    }
  }

  // ── 3. Generate invite token and insert invite record ─────────────────
  const inviteToken = generateApprovalToken()
  const expiresAt = new Date()
  expiresAt.setDate(expiresAt.getDate() + APPROVAL_TOKEN_EXPIRY_DAYS)

  const { error: insertError } = await supabase.from('collaborator_invites').insert({
    collaborator_id: collaborator.id,
    inviting_user_id: invitingUserId,
    invited_email: collaborator.email,
    invite_token: inviteToken,
    status: 'pending',
    token_expires_at: expiresAt.toISOString(),
  })

  if (insertError) {
    return { ok: false, status: 500, error: insertError.message }
  }

  const inviteLink = buildCollaboratorInviteUrl(inviteToken)

  // ── 4. Send educational IPI invite email (D-04, D-08) — best-effort. ──
  const email = buildCollaboratorInviteEmail({ name: collaborator.name, token: inviteToken })
  const result = await sendEmail({ to: collaborator.email, ...email })

  // A sendEmail failure lowers emailSent and nothing else — it is never
  // promoted to an error status, because a link the artist can
  // hand-deliver is still a working invite.
  return { ok: true, outcome: 'invited', skipped: false, emailSent: result.ok, inviteLink }
}
