-- ============================================================
-- Funūn — Wave 2: Rights & Registration Rails (Phase 20: Profile Table Rename)
-- Migration 077: drop the artist_profiles compatibility view
--
-- Removes the temporary artist_profiles compat view (created by migration
-- 076) once the D-01/D-02 zero-downtime rename window has closed. This
-- file makes no table, function, or grant changes — the rename itself
-- (076) already moved every dependent object; this migration's only job
-- is to retire the transitional shim after old code has stopped needing
-- it.
--
-- PRECONDITION — this file MUST be pushed only after:
--   1. Migration 076 has applied successfully against the live remote
--      database (the rename + view + function repoints + grants are live)
--      and `supabase migration list` shows LOCAL=REMOTE through 076.
--   2. The code deploy that reads user_profiles directly (not through the
--      view) has shipped to production.
--   3. D-04's full smoke-test gate has passed: signup on all 3
--      handle_new_user branches (artist / industry / curator), public
--      profile (/u/[handle], /r/[projectId]), a split sheet, a Settings
--      rights save, a metadata/registration read, and confirmation that
--      the migration-076 NOTIFY pgrst schema reload took effect.
--   4. D-05's soak period has elapsed — the compat view has been kept
--      alive long enough for any old warm serverless instance to drain
--      (or a low-traffic window has been reached), so no straggler
--      instance still calling `artist_profiles` gets a relation-not-found
--      error the moment this migration lands.
--
-- Do NOT recreate artist_profiles for any purpose after this migration —
-- the rename is complete and user_profiles is the sole canonical name.
--
-- An executor agent must NEVER run `supabase db push` for this migration.
-- The live push is this phase's second human-gated checkpoint (plan
-- 20-04), applied strictly after 076, the code deploy, and the D-04/D-05
-- gates above — mirroring migrations 058/062/063/065/066/070/072/073/
-- 074/075/076's "do not push from an executor agent" convention.
-- ============================================================

DROP VIEW IF EXISTS public.artist_profiles;

NOTIFY pgrst, 'reload schema';
