-- ============================================================
-- Funūn — Phase 27 (artist-invite-only-onboarding): concurrency follow-up
-- Migration 101 — mint_or_rotate_artist_invite(...) atomic RPC
--
-- WHY: 27-CODEX-REVIEW.md's follow-up review (independent re-audit of the
-- B3/H1/M5 fix commits themselves) found the "atomic claim"
-- mintOrRotateInvite() actually shipped was NOT atomic:
--
--   HIGH — read-then-unconditional-update rotation race. rotateRow()
--   (lib/invites/mintInvite.ts, pre-fix ~:46) issues a plain SELECT to
--   find the pending row, then an UNCONDITIONAL UPDATE ... SET
--   invite_token = <new> keyed only on id+status — two concurrent callers
--   that both read the SAME expired row (broadcast fan-out, or a convert
--   racing an issue) each generate their OWN token and each UPDATE
--   succeeds (no compare-and-set against the row's prior token/expiry), so
--   the loser's freshly emailed link silently stops working the instant
--   the winner's UPDATE lands after it — a torn read/write, unlike the
--   23505 insert-conflict path, which already had a graceful fallback.
--
--   HIGH — the ILIKE wildcard (M1's original bug) was reintroduced in
--   mintInvite.ts (`.ilike('email', email)`, pre-fix ~:68/:105) without
--   the escaping helper lib/invites/allowlist.ts already established
--   (exactCaseInsensitiveEmailPattern()) — an email containing `%` or `_`
--   would match multiple/other rows instead of exactly one.
--
-- WHAT: mint_or_rotate_artist_invite(p_email, p_source,
-- p_invited_by_user_id, p_new_token, p_new_expires_at) — a single
-- INSERT ... ON CONFLICT (LOWER(email)) WHERE status='pending' DO UPDATE
-- statement targeting migration 099's partial unique index
-- (idx_artist_invites_pending_email_unique). ONE atomic, row-locked
-- statement replaces the JS-side select-then-branch entirely:
--
--   - No pending row exists     -> INSERT lands             -> 'created'.
--   - Pending row exists,
--     tokenless or expired      -> DO UPDATE rotates to the
--                                   caller-supplied candidate
--                                   token/expiry (row-locked for
--                                   the statement's duration — a
--                                   concurrent second caller
--                                   blocks on the row lock until
--                                   the first commits, then
--                                   re-evaluates the CASE against
--                                   the now just-rotated,
--                                   no-longer-expired row)        -> 'rotated'.
--   - Pending row exists,
--     still active               -> DO UPDATE keeps the existing
--                                    token/expiry (no-op write)   -> 'reused'.
--
-- The email match is the SAME `LOWER(email)` equality the partial unique
-- index and handle_new_user()'s gate already use — no ILIKE, no pattern
-- language. There is no longer a client-side SELECT to express with
-- `.ilike()` at all, closing the reintroduced wildcard bug as a direct
-- consequence of making the operation atomic (not a separate patch).
--
-- Candidate token/expiry are generated by the CALLER (lib/invites/
-- mintInvite.ts, via the existing generateApprovalToken()/
-- APPROVAL_TOKEN_EXPIRY_DAYS — crypto.randomBytes(32), unchanged) and
-- passed in as plain parameters rather than generated in plpgsql: keeps a
-- single source of truth for token generation (mirrors migration 100's
-- upsert_artist_waitlist(), which likewise takes caller-supplied p_name/
-- p_note rather than deriving them in SQL) and avoids reimplementing
-- Node's CSPRNG in plpgsql. The function decides ATOMICALLY whether that
-- candidate is actually used (created/rotated) or discarded (reused) — the
-- caller never has to guess, and two concurrent callers can never observe
-- inconsistent state relative to each other.
--
-- SECURITY DEFINER, search_path = '', service_role-only EXECUTE — mirrors
-- migrations 097/099/100's email_has_account()/upsert_artist_waitlist()
-- lockdown exactly. Never exposed to PostgREST directly; called only from
-- lib/invites/mintInvite.ts via the service-role client.
--
-- HUMAN-GATED — never `supabase db push` from an agent (matches Phases
-- 16/21/25/27/28's standing convention). Draft + test-only — the owner
-- reviews and pushes at this phase's blocking cutover checkpoint, alongside
-- 097/098/099/100.
-- ============================================================

CREATE OR REPLACE FUNCTION public.mint_or_rotate_artist_invite(
  p_email               TEXT,
  p_source              TEXT,
  p_invited_by_user_id  UUID,
  p_new_token           TEXT,
  p_new_expires_at      TIMESTAMPTZ
)
RETURNS TABLE (out_id UUID, out_invite_token TEXT, out_state TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  RETURN QUERY
  WITH ins AS (
    INSERT INTO public.artist_invites (email, status, source, invite_token, token_expires_at, invited_by_user_id)
    VALUES (p_email, 'pending', p_source, p_new_token, p_new_expires_at, p_invited_by_user_id)
    ON CONFLICT (pg_catalog.lower(email)) WHERE status = 'pending'
    DO UPDATE SET
      invite_token = CASE
        WHEN artist_invites.invite_token IS NULL
          OR (artist_invites.token_expires_at IS NOT NULL AND artist_invites.token_expires_at <= now())
        THEN EXCLUDED.invite_token
        ELSE artist_invites.invite_token
      END,
      token_expires_at = CASE
        WHEN artist_invites.invite_token IS NULL
          OR (artist_invites.token_expires_at IS NOT NULL AND artist_invites.token_expires_at <= now())
        THEN EXCLUDED.token_expires_at
        ELSE artist_invites.token_expires_at
      END,
      updated_at = CASE
        WHEN artist_invites.invite_token IS NULL
          OR (artist_invites.token_expires_at IS NOT NULL AND artist_invites.token_expires_at <= now())
        THEN now()
        ELSE artist_invites.updated_at
      END
    RETURNING id, invite_token, (xmax = 0) AS was_inserted
  )
  SELECT
    ins.id,
    ins.invite_token,
    CASE
      WHEN ins.was_inserted THEN 'created'
      WHEN ins.invite_token = p_new_token THEN 'rotated'
      ELSE 'reused'
    END
  FROM ins;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.mint_or_rotate_artist_invite(text, text, uuid, text, timestamptz) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.mint_or_rotate_artist_invite(text, text, uuid, text, timestamptz) TO service_role;

COMMENT ON FUNCTION public.mint_or_rotate_artist_invite(text, text, uuid, text, timestamptz) IS
  'Service-role-only atomic mint/rotate/reuse claim for artist_invites (Phase 27 follow-up review, 27-CODEX-REVIEW.md). Single INSERT ... ON CONFLICT (LOWER(email)) WHERE status=''pending'' DO UPDATE against migration 099''s partial unique index — replaces the race-prone JS select-then-branch (torn read/write on rotation) and the reintroduced ILIKE wildcard match. Caller supplies a candidate token/expiry; the function atomically decides created/rotated/reused. Never exposed to PostgREST directly.';

-- Function privilege changes affect what PostgREST exposes.
NOTIFY pgrst, 'reload schema';
